# -*- coding: utf-8 -*-
"""Polyana Tomaz

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dAiX6OH2QRz6wU1DuggRPFADBTbzx1aV
"""

import pandas as pd
import sklearn as sk

dados = '/content/base_dados_ia.xlsx'
df = pd.read_excel(dados)

df.head()
df.info()

print(df['resultado'].value_counts())

# Transformar aprovado em 1 e reprovado em 0
binario = {'Reprovado': 0, 'Aprovado': 1}
df['resultado'] = df['resultado'].map(binario)

print(df.head())

modelo = sk.linear_model.LogisticRegression()

X = df[['nota1', 'nota2', 'frequencia', 'horas_estudo']]
y = df['resultado']

X_train, X_test, y_train, y_test = sk.model_selection.train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)

modelo.fit(X_train, y_train)

predicoes = modelo.predict(X_test)

acuracia = sk.metrics.accuracy_score(y_test, predicoes)
print(f'Acurácia: {acuracia}')

print("Matriz de confusão:")
print(sk.metrics.confusion_matrix(y_test, predicoes))

print("\nRelatório de classificação:")
print(sk.metrics.classification_report(y_test, predicoes))

probabilidades = modelo.predict_proba(X_test)
probabilidade_aprovacao = probabilidades[:, 1]
print(probabilidade_aprovacao)