# -*- coding: utf-8 -*-
"""thais_lourenco_20240836579.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Lcun5ACnIyRfcaxrDa9csHBVkkJd8iKw

Respostas:
1. O modelo tem boa acurácia?
Sim, 81%. O modelo equilibra bem a identificação de aprovados  e reprovados, mostrando-se confiável.

2. Como interpretar a probabilidade?
A probabilidade representa a chance de aprovação. Valores > 50% indicam aprovação prevista, < 50% reprovação.

3. Riscos de erro/injustiça?
Sim, há riscos de falsos positivos (6 alunos) e falsos negativos (1 aluno). O modelo não considera fatores contextuais.

4. Melhorias possíveis:

-Coletar mais dados da classe aprovados.

-Incluir features como participação em monitorias.

-Testar outros algoritmos.

-Monitoramento de vieses.
"""

import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split, cross_val_score, StratifiedKFold
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
from sklearn.preprocessing import StandardScaler
from sklearn.feature_selection import SelectKBest, f_classif

df = pd.read_csv('DADOS ATIVIDADE - aula_ia_pratica.csv')
df['resultado_num'] = df['resultado'].map({'Reprovado': 0, 'Aprovado': 1})
df['freq_estudo_interacao'] = df['frequencia'] * df['horas_estudo']

# Tentar usar nota1 e nota2 também (já que estão disponíveis)
print("Analisando notas por resultado:")
print(df.groupby('resultado')[['nota1', 'nota2']].mean())

# Incluir todas as features numéricas
X = df[['frequencia', 'horas_estudo', 'nota1', 'nota2', 'freq_estudo_interacao']]
y = df['resultado_num']

# Removendo alunos com frequência muito baixa ou horas_estudo muito altas
mask = (X['frequencia'] >= 50) & (X['horas_estudo'] <= 20)
X = X[mask]
y = y[mask]
print(f"\nApós remover outliers: {len(X)} amostras")

# Normalizar os dados
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

# Dividir com estratificação para manter proporção das classes
X_train, X_test, y_train, y_test = train_test_split(
    X_scaled, y, test_size=0.3, random_state=42, stratify=y
)

# Estratégia 1: Ajustar o limiar de decisão
modelo = LogisticRegression(random_state=42, class_weight='balanced', C=0.1, max_iter=1000)
modelo.fit(X_train, y_train)

# Predizer probabilidades
y_pred_proba = modelo.predict_proba(X_test)

# Ajustar limiar de decisão
melhor_acuracia = 0
melhor_limiar = 0.5
melhor_pred = None

for limiar in np.arange(0.3, 0.8, 0.05):
    y_pred_temp = (y_pred_proba[:, 1] >= limiar).astype(int)
    acuracia_temp = accuracy_score(y_test, y_pred_temp)

    # Verificar recall da classe Aprovado
    cm_temp = confusion_matrix(y_test, y_pred_temp)
    if cm_temp.shape == (2, 2) and cm_temp[1, 1] + cm_temp[1, 0] > 0:
        recall_aprovado = cm_temp[1, 1] / (cm_temp[1, 1] + cm_temp[1, 0])

        print(f"Limiar: {limiar:.2f} | Acurácia: {acuracia_temp:.2f} | Recall Aprovado: {recall_aprovado:.2f}")

        # Priorizar recall da classe minoritária
        if recall_aprovado > 0.6 and acuracia_temp > melhor_acuracia:
            melhor_acuracia = acuracia_temp
            melhor_limiar = limiar
            melhor_pred = y_pred_temp

if melhor_pred is None:
    melhor_pred = (y_pred_proba[:, 1] >= 0.5).astype(int)
    melhor_limiar = 0.5

print(f"\nMelhor limiar encontrado: {melhor_limiar:.2f}")

# Avaliação final
print(f"\nAcurácia do modelo (limiar {melhor_limiar:.2f}): {accuracy_score(y_test, melhor_pred):.2f}")

print("\nRelatório de Classificação:")
print(classification_report(y_test, melhor_pred, target_names=['Reprovado', 'Aprovado']))

print("Matriz de Confusão:")
cm = confusion_matrix(y_test, melhor_pred)
print(cm)

# Interpretação
print("\nCoeficientes do modelo:")
coeficientes = pd.DataFrame({
    'Feature': X.columns,
    'Coeficiente': modelo.coef_[0]
}).sort_values('Coeficiente', ascending=False)
print(coeficientes)
print(f"Intercepto: {modelo.intercept_[0]:.4f}")

# Análise adicional: importância das features
print("\nImportância das features (valor absoluto dos coeficientes):")
coeficientes['Importancia'] = abs(coeficientes['Coeficiente'])
print(coeficientes.sort_values('Importancia', ascending=False))

# Validação cruzada para verificar robustez
print("\nValidação Cruzada (5 folds):")
scores = cross_val_score(modelo, X_scaled, y, cv=StratifiedKFold(n_splits=5, shuffle=True, random_state=42))
print(f"Acurácia média: {scores.mean():.2f} (+/- {scores.std() * 2:.2f})")